### ISSUE TITLE
DynamicProgress should take ownership over progressbars

### ISSUE THREAD

**Issue by Kicer86** [p-ranav/indicators#134]
I believe that DynamicProgress should take ownership (unique pointer) to progress bars it consumes.

According to examples user is meant to access progress bars via DynamicProgress instance, 
so progress bar object has no use after being added to DynamicProgress.

Current solution forces user to keep progress bar object alive as long as DynamicProgress is alive.
This is a bit of inconvenience.
For example when spawning dynamic set of tasks executed by a thread pool,
where each task creates a progress bar object, it is required to keep this object alive
after task execution, which may be cumbersome.

**Comment by szdytom** [comment]
Agree, `std::reference_wrapper<T>` is meant to be used as a function parameter to the constructor of `std::thread` and to functions like `std::make_pair` and `std::invoke`. We do not see the STL using it as anything other than a parameter type.

Saving `std::reference_wrapper` must be dealt with care since it can lead to dangling pointers very easily. For example, if the user saves its `Indicator` into a vector and does `dynamic_progress.push_back(indicators.back())`, the next time the vector realloc itself, the `reference_wrapper` become dangling.

**Comment by p-ranav** [comment]
Seems reasonable and makes sense, could you update the README as well @Kicer86? Thanks!

**Comment by Kicer86** [comment]
@p-ranav done
