### ISSUE TITLE
Autodetect terminal width

### ISSUE THREAD

**Issue by wolfv** [p-ranav/indicators#42]
Could be great to detect the terminal width automatically.

This has answers for Win and POSIX:
https://stackoverflow.com/questions/23369503/get-size-of-terminal-window-rows-columns

**Comment by p-ranav** [comment]
I've added code to get the terminal width (https://github.com/p-ranav/indicators/blob/master/include/indicators/terminal_size.hpp)

Now it'll take a little work to use it. Part of the problem is this:

```
{prefix} {start} {fill} {lead} {remaining} {end} {percentage} [{elapsed}<{remaining}] {postfix}
         ^^^^^^^^^^^^^ Bar Width ^^^^^^^^^^^^^^^   
```

Bar width doesn't cover prefix text, percentage, time meter or postfix text. So knowing terminal width isn't enough to properly "arrange" the bar in one terminal row. 

Some work will need to be done to calculate bar width from all the other configured options.

**Comment by wolfv** [comment]
sweet. yeah my solution is to have two string streams for pre- and postfix and fill them at first, then check their length and pushing all to cout, including the bar content.
