### ISSUE TITLE
You should check out block drawing characters for a smooth animation

### ISSUE THREAD

**Issue by mortie** [p-ranav/indicators#7]
Hi, just heard about this libray from CppCast, and it looks sweet. I wondered, have you heard of the block drawing characters at https://en.wikipedia.org/wiki/Block_Elements? There are characters for 1/8th width blocks, 2/8th width blocks, 3/8th width blocks, etc. which can be used to make really smooth progress bars. 

I used them for a progress bar I made for a python application:

![screen-rec](https://user-images.githubusercontent.com/3728194/70907080-31780d80-2008-11ea-8669-5394e7da219c.gif)

The first few characters are full-width blocks, while the last character is whichever block character appropriate.

**Comment by p-ranav** [comment]
I had redditor also send me [this link](https://mike42.me/blog/2018-06-make-better-cli-progress-bars-with-unicode-block-characters) regarding using unicode block characters for smooth looking progress bars. 

The current API is probably not sufficient to support this because the leading character is chosen from the list `[" ", "▏", "▎", "▍", "▌", "▋", "▊", "▉"]` based on remaining progress.

**Comment by p-ranav** [comment]
Since this will change the update logic, I'll probably create a subclass of `ProgressBar`, probably called `BlockProgressBar`, that implements this bar.
